import Link from "next/link"
import "../styles/styles.css"
import Nav from "@/components/Nav"
import { Urbanist } from "@next/font/google"

const fuente = Urbanist({
  weight: "400",
  subsets: ["latin"],
})

export const metadata = {
  title: 'APRENDIENDO NEXT.JS',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className={fuente.className}>
          {children}
        </div>
      </body>
    </html>
  )
}
